name: Build and Deploy React Project
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Change working directory to client folder
      run: cd frontend
    - name: Install dependencies
      run: npm install
      working-directory: ./frontend
    - name: Build React project
      run: npm run build
      working-directory: ./frontend
    - name: Copy build artifacts to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: build/
        script: |
          rm -rf /home/${{ secrets.SSH_USER }}/chess/frontend/*
          scp -r build/* /home/${{ secrets.SSH_USER }}/chess/frontend/
